### ISSUE TITLE
The pretrained file may be broken

### ISSUE THREAD

**Issue by tsiendragon** [cvlab-stonybrook/DewarpNet#13]
Traceback (most recent call last):
  File "infer.py", line 129, in <module>
    test(args,img_path,fname)
  File "infer.py", line 80, in test
    bm_state = convert_state_dict(torch.load(args.bm_model_path, map_location='cpu')['model_state'])
  File "/root/anaconda3/envs/dewarpnet/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/dewarpnet/lib/python3.6/site-packages/torch/serialization.py", line 780, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 20942 more bytes. The file might be corrupted.

Do you want to replace the file?

**Comment by fh2019ustc** [comment]
My downloaded pretrained file is not broken. May be you can download again in case that the download process broken the model file.
