### ISSUE TITLE
Can't make work pre-trained model

### ISSUE THREAD

**Issue by fraps12** [cvlab-stonybrook/DewarpNet#36]
Hello,

I downloaded model made all path's and while running infer.py i got a error
`Read Input Image from : ./eval/inp/13_2 copy.png
Traceback (most recent call last):
  File "infer.py", line 129, in <module>
    test(args,img_path,fname)
  File "infer.py", line 76, in test
    wc_model.load_state_dict(wc_state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for dnetccnl:
        size mismatch for decoder.main.15.weight: copying a param with shape torch.Size([32, 2, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
`

After changing in densenetccnl i get another error
`Traceback (most recent call last):
  File "infer.py", line 129, in <module>
    test(args,img_path,fname)
  File "infer.py", line 97, in test
    outputs_bm = bm_model(bm_input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\urchin\pyprojects\DewarpNet-master\models\densenetccnl.py", line 239, in forward
    encoded=self.encoder(inputs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\urchin\pyprojects\DewarpNet-master\models\densenetccnl.py", line 165, in forward
    output = self.main(input).view(-1,self.ndim)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\batchnorm.py", line 135, in forward
    return F.batch_norm(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\functional.py", line 2149, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 4 elements not 5
`

I can't figure out what layer is failing. Can you help me to figure this out. Thanks in advance

**Comment by sagniklp** [comment]
I think it is a problem with the number of channels in input or output, please recheck.
Input and output of the shape network is 3 channels, texture mapping network takes 3 channels and outputs 2 channels.
